FROM traccar/traccar:latest

# 1. Clear out the existing official files to prevent conflicts
RUN rm -rf /opt/traccar/lib
RUN rm /opt/traccar/tracker-server.jar

# 2. Copy the library folder generated by your build
# (This was the missing piece causing the crash)
COPY target/lib /opt/traccar/lib

# 3. Copy your custom main application jar
COPY target/tracker-server.jar /opt/traccar/tracker-server.jar

# 4. Open ports
EXPOSE 8082 5000-5150 5000-5150/udp